/* ─── COOKBOOK ─────────────────────────────────────────────────────── */
/* Private recipe collection. Every recipe is built for a cut: high protein,
   calorie conscious, whole food ingredients, portioned per serving.

   Built for meal prep. Each recipe `makes` a batch of N servings, and both
   `macros` and `micros` are stored PER SERVING, never per batch. That is the
   unit the tracker multiplies by servings eaten, so keep it that way.

   All nutrition values are estimates.

   `image` paths are placeholders under /public/images/Cookbook/ and follow the
   same convention as the portfolio items in constants.js. Swap them any time,
   the filename matches the recipe id. */

export const CUISINES = [
  { id: "puerto-rican",   name: "Puerto Rican",   note: "Sofrito, citrus, adobo" },
  { id: "cuban",          name: "Cuban",          note: "Mojo, cumin, slow braise" },
  { id: "french",         name: "French",         note: "Herbs, mustard, clean technique" },
  { id: "thai",           name: "Thai",           note: "Lime, chili, fish sauce" },
  { id: "indian",         name: "Indian",         note: "Yogurt marinades, dry spice" },
  { id: "mexican",        name: "Mexican",        note: "Chile, lime, charred heat" },
  { id: "japanese",       name: "Japanese",       note: "Miso, dashi, clean grill" },
  { id: "italian",        name: "Italian",        note: "Tomato, herb, olive oil" },
  { id: "chinese",        name: "Chinese",        note: "High heat, ginger, garlic" },
  { id: "vietnamese",     name: "Vietnamese",     note: "Herbs, broth, nuoc cham" },
  { id: "korean",         name: "Korean",         note: "Gochujang, sesame, ferment" },
  { id: "greek",          name: "Greek",          note: "Lemon, oregano, yogurt" },
  { id: "middle-eastern", name: "Middle Eastern", note: "Sumac, tahini, char" },
  { id: "brazilian",      name: "Brazilian",      note: "Grill, lime, vinagrete" },
  { id: "spanish",        name: "Spanish",        note: "Garlic, paprika, plancha" },
  { id: "african",        name: "African",        note: "Peri peri, berbere, tagine" },
];

export const RECIPES = [
  /* ─── PUERTO RICAN ───────────────────────────────────────────────── */
  {
    id: "pr-pollo-guisado",
    cuisine: "puerto-rican",
    name: "Pollo Guisado Ligero",
    blurb: "The classic braise with the skin off and the oil cut back.",
    image: "/images/Cookbook/pr-pollo-guisado.jpg",
    macros: { calories: 405, protein: 47, carbs: 26, fat: 12 },
    micros: { fiber: 3, sodium: 720, sugar: 4, potassium: 980, calcium: 45, iron: 3.1, vitaminC: 22 },
    prep: "15 min", cook: "35 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs, trimmed",
      "1/4 cup sofrito",
      "1 tbsp olive oil",
      "1 can (8 oz) tomato sauce, no sugar added",
      "1 lb baby potatoes, halved",
      "1 tsp adobo seasoning",
      "1 tsp dried oregano",
      "1 packet sazon con culantro y achiote",
      "2 bay leaves",
      "1/4 cup pitted green olives",
      "1.5 cups low sodium chicken broth",
    ],
    steps: [
      "Pat the chicken dry and season it with adobo and oregano. Let it sit 10 minutes.",
      "Heat the olive oil in a heavy pot over medium high. Sear the chicken in a single layer, 3 minutes per side, then set it aside.",
      "Drop the heat to medium. Add the sofrito and cook 2 minutes until it stops smelling raw.",
      "Stir in the sazon and tomato sauce. Cook 2 minutes so it darkens.",
      "Return the chicken with the broth, potatoes, bay leaves, and olives. Bring to a simmer.",
      "Cover and simmer 25 minutes, until the potatoes give to a fork and the chicken pulls apart.",
      "Uncover and simmer 5 more minutes to tighten the sauce. Pull the bay leaves before serving.",
    ],
  },
  {
    id: "pr-bistec-encebollado",
    cuisine: "puerto-rican",
    name: "Bistec Encebollado",
    blurb: "Thin steak and onions in vinegar and garlic. Fifteen minutes start to finish.",
    image: "/images/Cookbook/pr-bistec-encebollado.jpg",
    macros: { calories: 340, protein: 42, carbs: 11, fat: 14 },
    micros: { fiber: 2, sodium: 580, sugar: 5, potassium: 760, calcium: 40, iron: 3.4, vitaminC: 9 },
    prep: "20 min", cook: "12 min", makes: 4,
    ingredients: [
      "1.5 lb top round steak, sliced thin against the grain",
      "2 large yellow onions, sliced into rings",
      "6 garlic cloves, minced",
      "1/4 cup white vinegar",
      "1 tbsp olive oil",
      "1 tsp adobo seasoning",
      "1 tsp dried oregano",
      "1/2 cup low sodium beef broth",
      "Black pepper to taste",
    ],
    steps: [
      "Toss the steak with garlic, vinegar, adobo, oregano, and pepper. Marinate 20 minutes at room temperature.",
      "Heat the oil in a wide skillet over high until it shimmers.",
      "Lift the steak out of the marinade and sear it in two batches, 90 seconds per side. Set it aside. Keep the marinade.",
      "Add the onions to the same pan. Cook 5 minutes until they soften and pick up color.",
      "Pour in the reserved marinade and the broth. Scrape the browned bits off the bottom.",
      "Return the steak and any resting juices. Simmer 2 minutes, no longer, or the round toughens.",
      "Serve the onions spooned over the steak.",
    ],
  },
  {
    id: "pr-arroz-gandules-coliflor",
    cuisine: "puerto-rican",
    name: "Arroz con Gandules de Coliflor",
    blurb: "Cauliflower rice standing in for the real thing. The sofrito does the work.",
    image: "/images/Cookbook/pr-arroz-gandules-coliflor.jpg",
    macros: { calories: 290, protein: 31, carbs: 18, fat: 11 },
    micros: { fiber: 7, sodium: 690, sugar: 6, potassium: 900, calcium: 70, iron: 2.6, vitaminC: 66 },
    prep: "10 min", cook: "18 min", makes: 4,
    ingredients: [
      "1 lb ground chicken breast",
      "24 oz riced cauliflower, fresh or thawed",
      "1 can (15 oz) pigeon peas, drained and rinsed",
      "1/3 cup sofrito",
      "1 packet sazon con culantro y achiote",
      "1 tbsp olive oil",
      "1/4 cup pitted green olives, sliced",
      "1 tsp dried oregano",
      "1/2 cup low sodium chicken broth",
      "Fresh cilantro to finish",
    ],
    steps: [
      "Heat the oil in a large skillet over medium high. Brown the ground chicken, breaking it apart, about 6 minutes.",
      "Push the chicken to one side. Add the sofrito to the open space and cook 2 minutes.",
      "Stir in the sazon and oregano until everything turns orange.",
      "Add the pigeon peas, olives, and broth. Simmer 3 minutes.",
      "Fold in the cauliflower rice. Cook 6 minutes uncovered, stirring twice, so the moisture cooks off instead of steaming.",
      "Taste for salt, then finish with chopped cilantro.",
    ],
  },

  /* ─── CUBAN ──────────────────────────────────────────────────────── */
  {
    id: "cu-ropa-vieja",
    cuisine: "cuban",
    name: "Ropa Vieja Magra",
    blurb: "Flank steak shredded into peppers and tomato. Batch cook it on Sunday.",
    image: "/images/Cookbook/cu-ropa-vieja.jpg",
    macros: { calories: 375, protein: 44, carbs: 19, fat: 13 },
    micros: { fiber: 3, sodium: 640, sugar: 6, potassium: 950, calcium: 60, iron: 3.8, vitaminC: 78 },
    prep: "15 min", cook: "2 hr", makes: 6,
    ingredients: [
      "2.5 lb flank steak, trimmed of visible fat",
      "1 tbsp olive oil",
      "2 bell peppers, sliced",
      "1 large onion, sliced",
      "6 garlic cloves, minced",
      "1 can (14 oz) crushed tomatoes",
      "2 cups low sodium beef broth",
      "2 tsp ground cumin",
      "1 tsp dried oregano",
      "2 bay leaves",
      "1/4 cup pimiento stuffed olives",
      "2 tbsp white vinegar",
    ],
    steps: [
      "Season the flank with salt, pepper, and 1 tsp of the cumin.",
      "Heat the oil in a Dutch oven over high. Sear the steak 4 minutes per side, then set it aside.",
      "Lower to medium. Cook the onion and peppers 8 minutes until they collapse.",
      "Add the garlic and remaining cumin. Cook 1 minute.",
      "Add the tomatoes, broth, oregano, and bay leaves. Return the steak and any juices.",
      "Cover and simmer low for 90 minutes, until the meat shreds under a fork with no resistance.",
      "Pull the steak out, shred it with two forks, and return it to the pot.",
      "Stir in the olives and vinegar. Simmer uncovered 15 minutes to concentrate. Pull the bay leaves.",
    ],
  },
  {
    id: "cu-pollo-plancha-mojo",
    cuisine: "cuban",
    name: "Pollo a la Plancha con Mojo",
    blurb: "Pressed chicken breast under a garlic citrus mojo. The leanest thing in the book.",
    image: "/images/Cookbook/cu-pollo-plancha-mojo.jpg",
    macros: { calories: 250, protein: 38, carbs: 6, fat: 8 },
    micros: { fiber: 1, sodium: 420, sugar: 3, potassium: 720, calcium: 30, iron: 1.3, vitaminC: 30 },
    prep: "30 min", cook: "10 min", makes: 4,
    ingredients: [
      "4 chicken breasts (6 oz each), butterflied thin",
      "1/2 cup fresh orange juice",
      "1/4 cup fresh lime juice",
      "8 garlic cloves, minced",
      "1 tbsp olive oil",
      "1 tsp ground cumin",
      "1 tsp dried oregano",
      "1/2 tsp salt",
      "1/4 cup chopped fresh cilantro",
    ],
    steps: [
      "Whisk the orange juice, lime juice, half the garlic, cumin, oregano, and salt into a marinade.",
      "Pour two thirds over the chicken and marinate 30 minutes. Do not go past an hour or the citrus turns the texture chalky.",
      "Warm the olive oil in a small pan over low. Add the remaining garlic and cook 60 seconds, just to take the edge off.",
      "Kill the heat and stir the reserved marinade into the garlic oil. That is the mojo.",
      "Heat a grill pan or skillet over high. Cook the chicken 3 to 4 minutes per side until the internal temperature hits 165F.",
      "Rest 5 minutes, then spoon the mojo over the top and finish with cilantro.",
    ],
  },
  {
    id: "cu-picadillo",
    cuisine: "cuban",
    name: "Picadillo de Pavo",
    blurb: "Ground turkey picadillo. Raisins and olives keep it honest.",
    image: "/images/Cookbook/cu-picadillo.jpg",
    macros: { calories: 280, protein: 32, carbs: 20, fat: 8 },
    micros: { fiber: 3, sodium: 690, sugar: 8, potassium: 780, calcium: 50, iron: 2.6, vitaminC: 40 },
    prep: "10 min", cook: "25 min", makes: 4,
    ingredients: [
      "1.5 lb 93% lean ground turkey",
      "1 tbsp olive oil",
      "1 onion, diced",
      "1 green bell pepper, diced",
      "4 garlic cloves, minced",
      "1 can (8 oz) tomato sauce",
      "2 tsp ground cumin",
      "1 tsp dried oregano",
      "1/4 cup pimiento stuffed olives, sliced",
      "2 tbsp raisins",
      "2 tbsp white vinegar",
      "1 bay leaf",
    ],
    steps: [
      "Heat the oil over medium high. Cook the onion and pepper 6 minutes.",
      "Add the garlic and cook 1 minute.",
      "Add the turkey. Break it up and brown it hard, about 8 minutes. Let it sit undisturbed for stretches so it colors instead of steams.",
      "Stir in the cumin and oregano. Cook 1 minute.",
      "Add the tomato sauce, olives, raisins, vinegar, and bay leaf.",
      "Simmer uncovered 10 minutes until the liquid tightens around the meat. Pull the bay leaf.",
      "Serve over cauliflower rice or a half cup of black beans.",
    ],
  },

  /* ─── FRENCH ─────────────────────────────────────────────────────── */
  {
    id: "fr-poulet-vinaigre",
    cuisine: "french",
    name: "Poulet au Vinaigre",
    blurb: "Chicken in a sharp vinegar pan sauce. No cream, no butter mountain.",
    image: "/images/Cookbook/fr-poulet-vinaigre.jpg",
    macros: { calories: 355, protein: 48, carbs: 7, fat: 14 },
    micros: { fiber: 1, sodium: 560, sugar: 2, potassium: 640, calcium: 35, iron: 2.2, vitaminC: 6 },
    prep: "10 min", cook: "30 min", makes: 4,
    ingredients: [
      "8 boneless skinless chicken thighs",
      "1 tbsp olive oil",
      "6 garlic cloves, smashed",
      "1/3 cup red wine vinegar",
      "1 cup low sodium chicken broth",
      "2 tbsp tomato paste",
      "2 sprigs fresh thyme",
      "1 tbsp Dijon mustard",
      "1 tsp unsalted butter",
      "Salt and black pepper",
    ],
    steps: [
      "Season the thighs on both sides. Heat the oil in a skillet over medium high.",
      "Sear the thighs 5 minutes per side until deeply browned. Set them aside.",
      "Lower to medium. Add the garlic and cook 2 minutes without letting it burn.",
      "Pour in the vinegar. Let it reduce by half, about 2 minutes. Stand back, it will be sharp.",
      "Whisk in the tomato paste, broth, and thyme.",
      "Return the chicken. Simmer uncovered 15 minutes, turning once.",
      "Move the chicken to plates. Whisk the Dijon and butter into the sauce off the heat until it turns glossy.",
      "Spoon the sauce over the chicken.",
    ],
  },
  {
    id: "fr-salade-nicoise",
    cuisine: "french",
    name: "Salade Nicoise au Thon Saisi",
    blurb: "Seared tuna instead of canned. Built as a full meal, not a side.",
    image: "/images/Cookbook/fr-salade-nicoise.jpg",
    macros: { calories: 420, protein: 46, carbs: 24, fat: 16 },
    micros: { fiber: 5, sodium: 520, sugar: 6, potassium: 1150, calcium: 90, iron: 3, vitaminC: 38 },
    prep: "15 min", cook: "12 min", makes: 2,
    ingredients: [
      "2 ahi tuna steaks (6 oz each)",
      "8 oz baby potatoes, halved",
      "4 oz green beans, trimmed",
      "2 eggs",
      "4 cups mixed greens",
      "1 cup cherry tomatoes, halved",
      "2 tbsp nicoise olives",
      "1 tbsp olive oil",
      "2 tbsp red wine vinegar",
      "1 tsp Dijon mustard",
      "1 tsp olive oil for searing",
    ],
    steps: [
      "Boil the potatoes 12 minutes. Add the green beans for the last 3 minutes, then drain both and run them under cold water.",
      "Boil the eggs 8 minutes for a set yolk with a soft center. Cool, peel, and halve.",
      "Whisk the vinegar, Dijon, and 1 tbsp olive oil into a vinaigrette.",
      "Pat the tuna bone dry and season it hard with salt and pepper.",
      "Heat 1 tsp oil in a skillet over high until it smokes. Sear the tuna 90 seconds per side for rare in the middle.",
      "Rest the tuna 3 minutes, then slice it against the grain.",
      "Build the plate: greens, then potatoes, beans, tomatoes, olives, and eggs in groups.",
      "Lay the tuna over the top and dress the whole thing right before eating.",
    ],
  },
  {
    id: "fr-cabillaud-papillote",
    cuisine: "french",
    name: "Cabillaud en Papillote",
    blurb: "Cod steamed in parchment. Zero added fat and nothing to clean.",
    image: "/images/Cookbook/fr-cabillaud-papillote.jpg",
    macros: { calories: 225, protein: 31, carbs: 12, fat: 6 },
    micros: { fiber: 4, sodium: 380, sugar: 4, potassium: 980, calcium: 80, iron: 1.2, vitaminC: 22 },
    prep: "10 min", cook: "18 min", makes: 2,
    ingredients: [
      "2 cod fillets (6 oz each)",
      "1 leek, white part only, sliced thin",
      "1 fennel bulb, shaved",
      "1 lemon, sliced thin",
      "2 sprigs fresh tarragon",
      "2 tsp olive oil",
      "2 tbsp dry white wine",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 400F. Cut two large squares of parchment paper.",
      "Pile the leek and fennel in the center of each square. Drizzle 1 tsp oil over each pile.",
      "Season the cod and set it on the vegetables.",
      "Top each fillet with lemon slices, a tarragon sprig, and 1 tbsp wine.",
      "Fold the parchment over and crimp the edges tight in overlapping folds. The packet has to hold steam.",
      "Bake 16 to 18 minutes. The packets will puff.",
      "Cut them open at the table. Watch the steam on the first cut.",
    ],
  },

  /* ─── THAI ───────────────────────────────────────────────────────── */
  {
    id: "th-larb-gai",
    cuisine: "thai",
    name: "Larb Gai",
    blurb: "Chicken larb. Almost no fat and it still hits harder than most things.",
    image: "/images/Cookbook/th-larb-gai.jpg",
    macros: { calories: 285, protein: 45, carbs: 10, fat: 7 },
    micros: { fiber: 2, sodium: 980, sugar: 3, potassium: 680, calcium: 45, iron: 1.8, vitaminC: 14 },
    prep: "15 min", cook: "10 min", makes: 4,
    ingredients: [
      "1.5 lb ground chicken breast",
      "3 tbsp fish sauce",
      "3 tbsp fresh lime juice",
      "2 tbsp toasted rice powder",
      "1 to 2 tsp chili flakes",
      "4 shallots, sliced thin",
      "3 scallions, sliced",
      "1/2 cup fresh mint leaves",
      "1/2 cup fresh cilantro",
      "1/4 cup water",
      "Butter lettuce leaves for serving",
    ],
    steps: [
      "If you do not have rice powder, toast 2 tbsp raw jasmine rice in a dry pan until deep brown, then grind it to sand in a spice grinder.",
      "Heat a skillet over medium high with the water, no oil. Add the chicken.",
      "Break the chicken into fine crumbles and cook 8 minutes until no pink remains. The water keeps it from clumping.",
      "Pull the pan off the heat and let it cool 2 minutes so the herbs do not wilt to nothing.",
      "Add the fish sauce, lime juice, rice powder, and chili flakes. Toss well.",
      "Fold in the shallots, scallions, mint, and cilantro.",
      "Taste and adjust. It should read sour first, then salty, then hot.",
      "Spoon into lettuce cups.",
    ],
  },
  {
    id: "th-tom-yum-goong",
    cuisine: "thai",
    name: "Tom Yum Goong",
    blurb: "Clear version, no coconut milk. A full bowl for under 200 calories.",
    image: "/images/Cookbook/th-tom-yum-goong.jpg",
    macros: { calories: 170, protein: 23, carbs: 11, fat: 4 },
    micros: { fiber: 2, sodium: 1120, sugar: 4, potassium: 560, calcium: 80, iron: 1.5, vitaminC: 12 },
    prep: "10 min", cook: "20 min", makes: 4,
    ingredients: [
      "1 lb large shrimp, peeled and deveined, shells reserved",
      "6 cups low sodium chicken broth",
      "3 stalks lemongrass, bruised and cut into 2 inch pieces",
      "6 kaffir lime leaves, torn",
      "4 slices fresh galangal or ginger",
      "8 oz mushrooms, halved",
      "3 tbsp fish sauce",
      "1/4 cup fresh lime juice",
      "3 Thai chilies, crushed",
      "1 tbsp chili paste in soybean oil",
      "Fresh cilantro to finish",
    ],
    steps: [
      "Toast the reserved shrimp shells in a dry pot 2 minutes until they turn pink and smell sweet.",
      "Add the broth, lemongrass, lime leaves, and galangal. Simmer 15 minutes.",
      "Strain out the solids and return the broth to the pot. This step is what separates a good tom yum from a cloudy one.",
      "Bring back to a simmer. Add the mushrooms and cook 3 minutes.",
      "Add the shrimp and cook 2 minutes, until they curl and turn opaque. Do not go longer.",
      "Kill the heat. Stir in the fish sauce, lime juice, chilies, and chili paste.",
      "Taste and balance. Finish with cilantro.",
    ],
  },
  {
    id: "th-pad-krapow",
    cuisine: "thai",
    name: "Pad Krapow Gai",
    blurb: "Thai basil chicken. Ten minutes and one pan.",
    image: "/images/Cookbook/th-pad-krapow.jpg",
    macros: { calories: 310, protein: 44, carbs: 9, fat: 11 },
    micros: { fiber: 3, sodium: 940, sugar: 4, potassium: 700, calcium: 70, iron: 2.1, vitaminC: 12 },
    prep: "8 min", cook: "10 min", makes: 4,
    ingredients: [
      "1.5 lb ground chicken breast",
      "1 tbsp avocado oil",
      "6 garlic cloves, minced",
      "4 Thai chilies, minced",
      "2 tbsp oyster sauce",
      "1 tbsp fish sauce",
      "1 tbsp low sodium soy sauce",
      "1 tsp coconut sugar",
      "2 cups Thai holy basil leaves, packed",
      "1/4 cup low sodium chicken broth",
      "1 cup green beans, cut into 1 inch pieces",
    ],
    steps: [
      "Mix the oyster sauce, fish sauce, soy sauce, and coconut sugar in a small bowl. Set it within reach, this cooks fast.",
      "Heat the oil in a wok or wide skillet over high until it just starts to smoke.",
      "Add the garlic and chilies. Stir 20 seconds.",
      "Add the chicken. Press it flat and let it sit 2 minutes to brown, then break it apart and cook 4 more minutes.",
      "Add the green beans and broth. Cook 2 minutes.",
      "Pour in the sauce mixture and toss 1 minute until it coats everything.",
      "Kill the heat and fold in the basil. It should wilt from residual heat only.",
      "Serve immediately over cauliflower rice or a half cup of jasmine rice.",
    ],
  },

  /* ─── INDIAN ─────────────────────────────────────────────────────── */
  {
    id: "in-chicken-tikka",
    cuisine: "indian",
    name: "Chicken Tikka",
    blurb: "Yogurt marinated and broiled. No cream sauce, all the spice.",
    image: "/images/Cookbook/in-chicken-tikka.jpg",
    macros: { calories: 295, protein: 50, carbs: 8, fat: 7 },
    micros: { fiber: 1, sodium: 680, sugar: 4, potassium: 720, calcium: 110, iron: 1.9, vitaminC: 6 },
    prep: "4 hr", cook: "15 min", makes: 4,
    ingredients: [
      "2 lb chicken breast, cut into 2 inch cubes",
      "1 cup nonfat Greek yogurt",
      "2 tbsp fresh lemon juice",
      "1 tbsp ginger paste",
      "1 tbsp garlic paste",
      "2 tsp garam masala",
      "2 tsp ground cumin",
      "2 tsp paprika",
      "1 tsp ground turmeric",
      "1 tsp cayenne",
      "1 tsp salt",
      "1 tsp kasuri methi, crushed",
    ],
    steps: [
      "Whisk the yogurt with the lemon juice, ginger, garlic, and every spice.",
      "Fold in the chicken until each piece is coated. Refrigerate at least 4 hours, overnight is better.",
      "Heat the broiler to high and set a rack 6 inches below it. Line a sheet pan with foil and set a wire rack on top.",
      "Thread the chicken onto skewers or spread it on the rack in a single layer with space between pieces.",
      "Broil 7 minutes. Flip and broil 6 to 8 more, until the edges char in spots.",
      "Rest 5 minutes before serving. Squeeze fresh lemon over the top.",
    ],
  },
  {
    id: "in-chana-masala",
    cuisine: "indian",
    name: "Chana Masala",
    blurb: "Chickpeas built out with fiber. Pair with a grilled protein on a heavy training day.",
    image: "/images/Cookbook/in-chana-masala.jpg",
    macros: { calories: 255, protein: 10, carbs: 40, fat: 6 },
    micros: { fiber: 11, sodium: 420, sugar: 7, potassium: 640, calcium: 90, iron: 3.4, vitaminC: 14 },
    prep: "10 min", cook: "30 min", makes: 4,
    ingredients: [
      "2 cans (15 oz each) chickpeas, drained and rinsed",
      "1 tbsp avocado oil",
      "1 large onion, diced fine",
      "1 tbsp ginger, minced",
      "4 garlic cloves, minced",
      "1 can (14 oz) diced tomatoes",
      "2 tsp ground coriander",
      "2 tsp ground cumin",
      "1 tsp ground turmeric",
      "1 tsp garam masala",
      "1 tsp amchur (dried mango powder)",
      "1/2 tsp cayenne",
      "1 cup water",
      "Fresh cilantro to finish",
    ],
    steps: [
      "Heat the oil over medium. Cook the onion 10 minutes until it goes past soft and starts browning at the edges. This is where the flavor comes from, do not rush it.",
      "Add the ginger and garlic. Cook 2 minutes.",
      "Add the coriander, cumin, turmeric, and cayenne. Stir 30 seconds until fragrant.",
      "Add the tomatoes and cook 8 minutes, mashing them down, until the oil separates at the edges.",
      "Add the chickpeas and water. Simmer 12 minutes.",
      "Mash about a quarter of the chickpeas against the side of the pot to thicken the sauce.",
      "Stir in the garam masala and amchur. Finish with cilantro.",
    ],
  },
  {
    id: "in-tandoori-salmon",
    cuisine: "indian",
    name: "Tandoori Salmon with Raita",
    blurb: "Salmon under a dry spice crust with a cooling cucumber yogurt.",
    image: "/images/Cookbook/in-tandoori-salmon.jpg",
    macros: { calories: 315, protein: 34, carbs: 9, fat: 16 },
    micros: { fiber: 1, sodium: 380, sugar: 5, potassium: 900, calcium: 140, iron: 1.1, vitaminC: 5 },
    prep: "30 min", cook: "12 min", makes: 4,
    ingredients: [
      "4 salmon fillets (6 oz each)",
      "1/2 cup nonfat Greek yogurt",
      "1 tbsp lemon juice",
      "2 tsp tandoori masala",
      "1 tsp ground cumin",
      "1 tsp paprika",
      "1/2 tsp cayenne",
      "1 tsp ginger garlic paste",
      "1 cup nonfat Greek yogurt for the raita",
      "1 Persian cucumber, grated and squeezed dry",
      "2 tbsp chopped mint",
      "1/2 tsp ground cumin for the raita",
    ],
    steps: [
      "Mix the 1/2 cup yogurt with lemon juice, tandoori masala, cumin, paprika, cayenne, and ginger garlic paste.",
      "Coat the salmon and marinate 30 minutes in the refrigerator. Any longer and the acid starts cooking it.",
      "Make the raita: stir the remaining yogurt with the squeezed cucumber, mint, and cumin. Salt to taste and chill it.",
      "Heat the oven to 425F. Line a sheet pan with foil.",
      "Set the salmon skin side down and roast 10 minutes.",
      "Switch to broil for the last 2 minutes to blister the crust.",
      "Serve with the raita spooned alongside, not over, so the crust stays intact.",
    ],
  },

  /* ─── MEXICAN ────────────────────────────────────────────────────── */
  {
    id: "mx-pollo-asado",
    cuisine: "mexican",
    name: "Pollo Asado Bowl",
    blurb: "Citrus and achiote chicken over a built bowl. Meal prep anchor.",
    image: "/images/Cookbook/mx-pollo-asado.jpg",
    macros: { calories: 425, protein: 51, carbs: 28, fat: 13 },
    micros: { fiber: 11, sodium: 560, sugar: 5, potassium: 1180, calcium: 90, iron: 3.6, vitaminC: 26 },
    prep: "2 hr", cook: "15 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "1/3 cup fresh orange juice",
      "1/4 cup fresh lime juice",
      "2 tbsp achiote paste",
      "4 garlic cloves, minced",
      "1 tsp ground cumin",
      "1 tsp dried oregano",
      "1 tbsp avocado oil",
      "2 cups cooked black beans",
      "4 cups shredded romaine",
      "1 cup pico de gallo",
      "1 avocado, sliced",
    ],
    steps: [
      "Blend the orange juice, lime juice, achiote paste, garlic, cumin, and oregano into a smooth marinade.",
      "Marinate the chicken at least 2 hours, up to overnight.",
      "Heat the oil in a cast iron skillet or grill over high.",
      "Cook the chicken 6 to 7 minutes per side until the edges char and the center reaches 175F.",
      "Rest 5 minutes, then slice against the grain.",
      "Build each bowl: romaine, then 1/2 cup black beans, then the chicken.",
      "Top with pico de gallo and a quarter of the avocado.",
    ],
  },
  {
    id: "mx-camarones-diabla",
    cuisine: "mexican",
    name: "Camarones a la Diabla",
    blurb: "Shrimp in a toasted chile sauce. Twenty minutes, very low calorie.",
    image: "/images/Cookbook/mx-camarones-diabla.jpg",
    macros: { calories: 245, protein: 38, carbs: 12, fat: 6 },
    micros: { fiber: 3, sodium: 720, sugar: 5, potassium: 520, calcium: 100, iron: 1.4, vitaminC: 30 },
    prep: "15 min", cook: "15 min", makes: 4,
    ingredients: [
      "1.5 lb large shrimp, peeled and deveined",
      "4 guajillo chiles, stemmed and seeded",
      "2 chiles de arbol, stemmed",
      "3 roma tomatoes, quartered",
      "1/2 onion, quartered",
      "3 garlic cloves",
      "1 tbsp avocado oil",
      "1 tsp ground cumin",
      "1/2 cup low sodium chicken broth",
      "1 tbsp fresh lime juice",
      "Salt to taste",
    ],
    steps: [
      "Toast the dried chiles in a dry skillet over medium, 30 seconds per side. Pull them the moment they smell nutty. Burnt chiles turn the whole sauce bitter.",
      "Cover the chiles with hot water and soak 15 minutes.",
      "In the same skillet, char the tomatoes, onion, and garlic until blackened in spots, about 8 minutes.",
      "Blend the drained chiles with the charred vegetables, cumin, and broth until smooth.",
      "Heat the oil over medium high. Pour in the sauce and fry it 5 minutes, stirring, until it darkens and thickens.",
      "Add the shrimp and cook 3 to 4 minutes, until just opaque.",
      "Finish with lime juice and salt.",
    ],
  },
  {
    id: "mx-tinga-pollo",
    cuisine: "mexican",
    name: "Tinga de Pollo",
    blurb: "Shredded chicken in chipotle and tomato. Serve in lettuce cups.",
    image: "/images/Cookbook/mx-tinga-pollo.jpg",
    macros: { calories: 310, protein: 51, carbs: 13, fat: 6 },
    micros: { fiber: 3, sodium: 620, sugar: 6, potassium: 820, calcium: 60, iron: 2, vitaminC: 18 },
    prep: "10 min", cook: "30 min", makes: 4,
    ingredients: [
      "2 lb chicken breast",
      "1 tbsp avocado oil",
      "1 large onion, sliced thin",
      "4 garlic cloves, minced",
      "1 can (14 oz) fire roasted diced tomatoes",
      "3 chipotle peppers in adobo, minced",
      "1 tbsp adobo sauce from the can",
      "1 tsp dried oregano",
      "1 tsp ground cumin",
      "1 cup low sodium chicken broth",
      "Butter lettuce leaves for serving",
      "Lime wedges",
    ],
    steps: [
      "Simmer the chicken breast in the broth with a pinch of salt, covered, for 18 minutes. Pull it out and shred it with two forks. Keep the broth.",
      "Heat the oil over medium high. Cook the onion 8 minutes until it browns at the edges.",
      "Add the garlic, oregano, and cumin. Cook 1 minute.",
      "Add the tomatoes, chipotles, and adobo sauce. Simmer 5 minutes.",
      "Blend the sauce smooth if you want it clean, or leave it rustic.",
      "Return the sauce to the pan with the shredded chicken and 1/2 cup of the reserved broth.",
      "Simmer 8 minutes until the chicken drinks up the sauce and the pan goes nearly dry.",
      "Spoon into lettuce cups with lime on the side.",
    ],
  },

  /* ─── JAPANESE ───────────────────────────────────────────────────── */
  {
    id: "jp-salmon-shioyaki",
    cuisine: "japanese",
    name: "Sake Shioyaki",
    blurb: "Salt grilled salmon. Two ingredients and a technique.",
    image: "/images/Cookbook/jp-salmon-shioyaki.jpg",
    macros: { calories: 280, protein: 34, carbs: 0, fat: 16 },
    micros: { fiber: 0, sodium: 640, sugar: 0, potassium: 780, calcium: 25, iron: 0.8, vitaminC: 4 },
    prep: "30 min", cook: "12 min", makes: 4,
    ingredients: [
      "4 salmon fillets (6 oz each), skin on",
      "2 tsp kosher salt",
      "2 tbsp sake",
      "1 lemon, wedged",
      "Grated daikon to serve",
    ],
    steps: [
      "Pat the salmon completely dry and rub it with sake. Wait 10 minutes, then pat dry again. The sake pulls out any fishiness.",
      "Salt both sides evenly and rest the fish uncovered in the refrigerator 20 minutes. Moisture will bead on the surface.",
      "Wipe the beads off. This is the step that gets you crisp skin.",
      "Heat the broiler or a grill pan to high.",
      "Cook skin side up first for 6 minutes, then flip and go 5 to 6 minutes on the skin.",
      "Serve with grated daikon and a lemon wedge.",
    ],
  },
  {
    id: "jp-chicken-teriyaki",
    cuisine: "japanese",
    name: "Chicken Teriyaki Donburi",
    blurb: "Teriyaki with the sugar cut down to a quarter of standard.",
    image: "/images/Cookbook/jp-chicken-teriyaki.jpg",
    macros: { calories: 400, protein: 48, carbs: 32, fat: 9 },
    micros: { fiber: 5, sodium: 820, sugar: 9, potassium: 880, calcium: 90, iron: 2.4, vitaminC: 82 },
    prep: "10 min", cook: "18 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "1/4 cup low sodium soy sauce",
      "1/4 cup mirin",
      "2 tbsp sake",
      "1 tbsp coconut sugar",
      "1 tsp grated ginger",
      "1 tsp avocado oil",
      "2 cups cooked short grain brown rice",
      "4 cups steamed broccoli",
      "2 scallions, sliced",
      "1 tsp toasted sesame seeds",
    ],
    steps: [
      "Whisk the soy sauce, mirin, sake, coconut sugar, and ginger together.",
      "Heat the oil in a skillet over medium high. Sear the thighs 5 minutes per side until browned through.",
      "Pour the sauce over the chicken. It will bubble hard.",
      "Simmer 6 minutes, spooning the sauce over the chicken repeatedly, until it thickens to a glaze that coats a spoon.",
      "Pull the chicken, rest it 3 minutes, then slice it.",
      "Build the bowls: 1/2 cup rice, 1 cup broccoli, then the sliced chicken.",
      "Spoon the remaining glaze over and finish with scallions and sesame seeds.",
    ],
  },
  {
    id: "jp-miso-cod",
    cuisine: "japanese",
    name: "Miso Glazed Cod",
    blurb: "The famous one, scaled back on sugar. Marinate a day ahead.",
    image: "/images/Cookbook/jp-miso-cod.jpg",
    macros: { calories: 210, protein: 31, carbs: 10, fat: 5 },
    micros: { fiber: 1, sodium: 780, sugar: 7, potassium: 620, calcium: 40, iron: 0.7, vitaminC: 2 },
    prep: "24 hr", cook: "10 min", makes: 4,
    ingredients: [
      "4 black cod or regular cod fillets (6 oz each)",
      "1/4 cup white miso paste",
      "3 tbsp mirin",
      "2 tbsp sake",
      "1 tbsp coconut sugar",
      "2 scallions, sliced",
    ],
    steps: [
      "Warm the mirin and sake in a small pan over medium for 20 seconds to cook off the alcohol.",
      "Whisk in the miso and coconut sugar until fully smooth. Cool it completely.",
      "Coat the cod in the marinade and refrigerate 24 hours in a sealed container.",
      "Wipe the marinade off the fillets. Leaving it on means it burns instead of caramelizes.",
      "Heat the broiler to high with a rack 6 inches down.",
      "Broil 7 to 9 minutes until the top blisters brown and the fish flakes.",
      "Finish with scallions.",
    ],
  },

  /* ─── ITALIAN ────────────────────────────────────────────────────── */
  {
    id: "it-chicken-piccata",
    cuisine: "italian",
    name: "Chicken Piccata",
    blurb: "Lemon and caper pan sauce with one tablespoon of butter across four plates.",
    image: "/images/Cookbook/it-chicken-piccata.jpg",
    macros: { calories: 275, protein: 38, carbs: 8, fat: 10 },
    micros: { fiber: 1, sodium: 620, sugar: 2, potassium: 700, calcium: 40, iron: 1.4, vitaminC: 8 },
    prep: "10 min", cook: "18 min", makes: 4,
    ingredients: [
      "4 chicken breasts (6 oz each), pounded to 1/2 inch",
      "2 tbsp almond flour",
      "1 tbsp olive oil",
      "3 garlic cloves, minced",
      "1/2 cup dry white wine",
      "1 cup low sodium chicken broth",
      "3 tbsp fresh lemon juice",
      "3 tbsp capers, drained",
      "1 tbsp unsalted butter",
      "1/4 cup chopped parsley",
    ],
    steps: [
      "Season the chicken and dust it lightly with almond flour. Shake off the excess.",
      "Heat the oil in a skillet over medium high. Cook the chicken 4 minutes per side until golden. Set it aside.",
      "Add the garlic to the pan and cook 30 seconds.",
      "Pour in the wine and scrape the browned bits loose. Reduce by half, about 2 minutes.",
      "Add the broth, lemon juice, and capers. Simmer 4 minutes until it reduces by a third.",
      "Kill the heat and swirl in the butter until the sauce goes glossy.",
      "Return the chicken to warm through, 1 minute, then finish with parsley.",
    ],
  },
  {
    id: "it-polpette-pomodoro",
    cuisine: "italian",
    name: "Polpette di Tacchino",
    blurb: "Turkey meatballs in a plain tomato sauce. Freezes well.",
    image: "/images/Cookbook/it-polpette-pomodoro.jpg",
    macros: { calories: 335, protein: 43, carbs: 16, fat: 11 },
    micros: { fiber: 4, sodium: 640, sugar: 9, potassium: 900, calcium: 150, iron: 3, vitaminC: 22 },
    prep: "15 min", cook: "35 min", makes: 4,
    ingredients: [
      "1.5 lb 93% lean ground turkey",
      "1 egg",
      "1/3 cup almond flour",
      "1/4 cup grated Parmesan",
      "3 garlic cloves, minced",
      "1/4 cup chopped parsley",
      "1 tsp dried oregano",
      "1 can (28 oz) crushed San Marzano tomatoes",
      "1 tbsp olive oil",
      "1/2 onion, diced fine",
      "Fresh basil to finish",
    ],
    steps: [
      "Mix the turkey, egg, almond flour, Parmesan, half the garlic, parsley, oregano, salt, and pepper. Work it just until combined. Overmixing makes them dense.",
      "Roll into 16 meatballs, about 1.5 inches each.",
      "Heat the oven to 400F. Bake the meatballs on a lined sheet pan 15 minutes.",
      "While they bake, heat the oil in a pot over medium. Cook the onion 5 minutes.",
      "Add the remaining garlic, cook 1 minute, then add the tomatoes. Season with salt.",
      "Simmer the sauce 15 minutes.",
      "Slide the baked meatballs into the sauce and simmer 10 more minutes.",
      "Finish with torn basil. Serve over zucchini noodles or a half cup of pasta.",
    ],
  },
  {
    id: "it-tonno-fagioli",
    cuisine: "italian",
    name: "Insalata di Tonno e Fagioli",
    blurb: "No cooking at all. Assemble it in five minutes at your desk.",
    image: "/images/Cookbook/it-tonno-fagioli.jpg",
    macros: { calories: 350, protein: 34, carbs: 30, fat: 11 },
    micros: { fiber: 9, sodium: 580, sugar: 4, potassium: 980, calcium: 120, iron: 3.6, vitaminC: 24 },
    prep: "10 min", cook: "0 min", makes: 2,
    ingredients: [
      "2 cans (5 oz each) tuna in water, drained",
      "1 can (15 oz) cannellini beans, drained and rinsed",
      "1/4 red onion, sliced paper thin",
      "1 cup cherry tomatoes, halved",
      "2 tbsp chopped parsley",
      "2 tbsp fresh lemon juice",
      "1 tbsp olive oil",
      "1 tsp red wine vinegar",
      "Salt and black pepper",
      "4 cups arugula",
    ],
    steps: [
      "Soak the sliced onion in cold water 10 minutes, then drain. This pulls the harsh bite out.",
      "Whisk the lemon juice, olive oil, vinegar, salt, and pepper together.",
      "Combine the tuna, beans, tomatoes, drained onion, and parsley in a bowl.",
      "Pour the dressing over and fold gently so the beans stay whole.",
      "Let it sit 10 minutes so the beans absorb the dressing.",
      "Serve over arugula.",
    ],
  },

  /* ─── CHINESE ────────────────────────────────────────────────────── */
  {
    id: "cn-beef-broccoli",
    cuisine: "chinese",
    name: "Beef and Broccoli",
    blurb: "Velveted flank steak. Restaurant texture without the deep fry.",
    image: "/images/Cookbook/cn-beef-broccoli.jpg",
    macros: { calories: 335, protein: 42, carbs: 16, fat: 11 },
    micros: { fiber: 4, sodium: 880, sugar: 4, potassium: 880, calcium: 80, iron: 3.2, vitaminC: 82 },
    prep: "20 min", cook: "12 min", makes: 4,
    ingredients: [
      "1.5 lb flank steak, sliced thin against the grain",
      "1 tbsp cornstarch",
      "1 tbsp low sodium soy sauce for the marinade",
      "1 tsp baking soda",
      "1 lb broccoli florets",
      "1 tbsp avocado oil",
      "4 garlic cloves, minced",
      "1 tbsp grated ginger",
      "3 tbsp low sodium soy sauce",
      "2 tbsp oyster sauce",
      "1 tbsp rice vinegar",
      "1 cup low sodium beef broth",
      "1 tsp cornstarch for the sauce",
      "1 tsp sesame oil",
    ],
    steps: [
      "Toss the sliced beef with 1 tbsp cornstarch, 1 tbsp soy sauce, and the baking soda. Rest 20 minutes. The baking soda is what makes it tender.",
      "Rinse the beef briefly and pat it dry. Do not skip the rinse or it tastes soapy.",
      "Whisk the sauce: 3 tbsp soy sauce, oyster sauce, rice vinegar, broth, and 1 tsp cornstarch.",
      "Blanch the broccoli in boiling water 90 seconds, then shock it in ice water and drain.",
      "Heat the oil in a wok over high until it smokes. Sear the beef in two batches, 90 seconds each, then set it aside.",
      "Add the garlic and ginger to the wok. Stir 20 seconds.",
      "Pour in the sauce and simmer 2 minutes until it thickens enough to coat a spoon.",
      "Return the beef and broccoli. Toss 1 minute, finish with sesame oil.",
    ],
  },
  {
    id: "cn-steamed-fish",
    cuisine: "chinese",
    name: "Ginger Scallion Steamed Fish",
    blurb: "Cantonese steamed fish. Lean, fast, and hard to overthink.",
    image: "/images/Cookbook/cn-steamed-fish.jpg",
    macros: { calories: 220, protein: 31, carbs: 4, fat: 9 },
    micros: { fiber: 1, sodium: 700, sugar: 2, potassium: 720, calcium: 45, iron: 0.9, vitaminC: 6 },
    prep: "10 min", cook: "12 min", makes: 4,
    ingredients: [
      "4 white fish fillets (6 oz each), sea bass or cod",
      "3 inch piece of ginger, julienned",
      "6 scallions, cut into 2 inch strips",
      "3 tbsp low sodium soy sauce",
      "1 tbsp water",
      "1 tsp coconut sugar",
      "2 tbsp avocado oil",
      "Fresh cilantro to finish",
    ],
    steps: [
      "Set up a steamer with an inch of boiling water underneath.",
      "Lay the fish on a heatproof plate. Scatter half the ginger over and under the fillets.",
      "Steam covered 8 to 10 minutes, until the flesh flakes at the thickest point.",
      "Pour off the milky liquid that collects on the plate. It tastes flat and will dilute the sauce.",
      "Warm the soy sauce, water, and coconut sugar in a small pan. Pour it around the fish, not over it.",
      "Pile the remaining ginger and all the scallions on top of the fish.",
      "Heat the oil in a small pan until it shimmers and just begins to smoke. Pour it directly over the scallions. It will crackle and bloom.",
      "Finish with cilantro and serve immediately.",
    ],
  },
  {
    id: "cn-kung-pao",
    cuisine: "chinese",
    name: "Kung Pao Chicken",
    blurb: "Cut back on peanuts and sugar, kept the numbing heat.",
    image: "/images/Cookbook/cn-kung-pao.jpg",
    macros: { calories: 345, protein: 45, carbs: 14, fat: 12 },
    micros: { fiber: 2, sodium: 760, sugar: 4, potassium: 700, calcium: 40, iron: 1.9, vitaminC: 5 },
    prep: "15 min", cook: "12 min", makes: 4,
    ingredients: [
      "1.5 lb chicken breast, cut into 3/4 inch cubes",
      "1 tbsp cornstarch",
      "1 tbsp Shaoxing wine",
      "1 tbsp avocado oil",
      "10 dried red chilies",
      "1 tsp Sichuan peppercorns",
      "4 garlic cloves, minced",
      "1 tbsp grated ginger",
      "3 scallions, cut into 1 inch pieces",
      "1/4 cup unsalted roasted peanuts",
      "2 tbsp low sodium soy sauce",
      "1 tbsp black vinegar",
      "1 tsp coconut sugar",
      "1/2 cup low sodium chicken broth",
    ],
    steps: [
      "Toss the chicken with the cornstarch and Shaoxing wine. Rest 15 minutes.",
      "Whisk the soy sauce, black vinegar, coconut sugar, and broth into a sauce.",
      "Heat the oil in a wok over high. Add the dried chilies and peppercorns and stir 20 seconds until fragrant. Pull them if they start to blacken.",
      "Add the chicken in a single layer. Let it sit 2 minutes to sear, then stir fry 4 minutes until cooked through.",
      "Add the garlic and ginger. Stir 30 seconds.",
      "Pour in the sauce and cook 2 minutes until it thickens and glazes the chicken.",
      "Toss in the scallions and peanuts off the heat.",
    ],
  },

  /* ─── VIETNAMESE ─────────────────────────────────────────────────── */
  {
    id: "vn-bun-ga-nuong",
    cuisine: "vietnamese",
    name: "Bun Ga Nuong",
    blurb: "Grilled lemongrass chicken over herbs and noodles. Heavy on the herbs.",
    image: "/images/Cookbook/vn-bun-ga-nuong.jpg",
    macros: { calories: 415, protein: 46, carbs: 35, fat: 10 },
    micros: { fiber: 3, sodium: 1020, sugar: 8, potassium: 780, calcium: 70, iron: 2.4, vitaminC: 14 },
    prep: "1 hr", cook: "15 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "3 stalks lemongrass, minced fine",
      "4 garlic cloves, minced",
      "2 tbsp fish sauce",
      "1 tbsp coconut sugar",
      "1 tbsp avocado oil",
      "6 oz rice vermicelli, cooked and cooled",
      "2 cups shredded lettuce",
      "1 cup bean sprouts",
      "1 cup mixed mint, cilantro, and Thai basil",
      "1 cucumber, julienned",
      "1/4 cup fish sauce, 1/4 cup lime juice, 2 tbsp coconut sugar, 1/2 cup water, 2 minced chilies for nuoc cham",
    ],
    steps: [
      "Blend the lemongrass, garlic, 2 tbsp fish sauce, 1 tbsp coconut sugar, and oil into a paste.",
      "Marinate the chicken at least 1 hour, ideally overnight.",
      "Make the nuoc cham: stir the water, coconut sugar, lime juice, and fish sauce until dissolved, then add the chilies. Taste and adjust, it should be balanced, not salty.",
      "Heat a grill or grill pan to high. Cook the chicken 6 minutes per side until charred at the edges.",
      "Rest 5 minutes, then slice.",
      "Build the bowls: vermicelli on the bottom, then lettuce, cucumber, sprouts, and a heavy handful of herbs.",
      "Lay the chicken over the top and pour nuoc cham over the whole bowl right before eating.",
    ],
  },
  {
    id: "vn-pho-ga",
    cuisine: "vietnamese",
    name: "Pho Ga",
    blurb: "Chicken pho. Char the aromatics or the broth tastes like nothing.",
    image: "/images/Cookbook/vn-pho-ga.jpg",
    macros: { calories: 350, protein: 42, carbs: 34, fat: 5 },
    micros: { fiber: 2, sodium: 980, sugar: 3, potassium: 640, calcium: 50, iron: 2, vitaminC: 8 },
    prep: "20 min", cook: "1 hr 30 min", makes: 4,
    ingredients: [
      "1 whole chicken (3 lb), or 3 lb chicken parts",
      "12 cups water",
      "1 large onion, halved",
      "4 inch piece of ginger, halved lengthwise",
      "6 whole star anise",
      "1 cinnamon stick",
      "4 whole cloves",
      "1 tbsp coriander seeds",
      "2 tbsp fish sauce",
      "1 tsp salt",
      "8 oz flat rice noodles",
      "Bean sprouts, Thai basil, lime, and jalapeno for serving",
    ],
    steps: [
      "Char the onion and ginger cut side down in a dry pan over high heat, 6 minutes, until blackened. This is not optional.",
      "Toast the star anise, cinnamon, cloves, and coriander in the same pan for 90 seconds.",
      "Bring the water to a boil, add the chicken, and boil hard for 3 minutes. Drain and rinse the chicken and the pot. This gets you a clear broth.",
      "Return the chicken with fresh water, the charred aromatics, and the toasted spices.",
      "Simmer low and uncovered for 1 hour. Skim the surface every 15 minutes.",
      "Pull the chicken out, let it cool, then shred the meat and discard the bones.",
      "Strain the broth through a fine mesh sieve. Season with fish sauce and salt.",
      "Cook the noodles separately. Divide them into bowls, add the shredded chicken, and ladle the boiling broth over.",
      "Serve with sprouts, basil, lime, and jalapeno on the side.",
    ],
  },
  {
    id: "vn-goi-cuon",
    cuisine: "vietnamese",
    name: "Goi Cuon",
    blurb: "Fresh shrimp rolls. Nothing fried, and they travel well.",
    image: "/images/Cookbook/vn-goi-cuon.jpg",
    macros: { calories: 230, protein: 26, carbs: 24, fat: 3 },
    micros: { fiber: 2, sodium: 720, sugar: 5, potassium: 420, calcium: 70, iron: 1.2, vitaminC: 12 },
    prep: "30 min", cook: "10 min", makes: 4,
    ingredients: [
      "1 lb large shrimp, peeled and deveined",
      "12 rice paper wrappers",
      "3 oz rice vermicelli, cooked and cooled",
      "1 head butter lettuce, leaves separated",
      "1 cup fresh mint leaves",
      "1 cup fresh cilantro",
      "1 cucumber, julienned",
      "2 tbsp fish sauce, 2 tbsp lime juice, 1 tbsp coconut sugar, 1/4 cup water, 1 minced chili for dipping",
    ],
    steps: [
      "Boil the shrimp 2 to 3 minutes until pink. Drain, cool, and slice each one in half lengthwise.",
      "Stir the dipping sauce ingredients until the sugar dissolves.",
      "Set up a station: a shallow dish of warm water, a damp towel as your work surface, and all the fillings in reach.",
      "Dip one rice paper in the warm water for 2 seconds. It should still feel stiff. It keeps softening on the towel.",
      "Lay 3 shrimp halves cut side down across the lower third, then add lettuce, noodles, cucumber, and herbs on top.",
      "Fold the bottom edge over the filling, fold in both sides, then roll tight to the top.",
      "Keep the finished rolls under a damp towel so they do not dry out and split.",
      "Serve with the dipping sauce.",
    ],
  },

  /* ─── KOREAN ─────────────────────────────────────────────────────── */
  {
    id: "kr-bulgogi-ssam",
    cuisine: "korean",
    name: "Bulgogi Ssam",
    blurb: "Lean sirloin bulgogi in lettuce wraps. Skip the rice on rest days.",
    image: "/images/Cookbook/kr-bulgogi-ssam.jpg",
    macros: { calories: 330, protein: 44, carbs: 14, fat: 11 },
    micros: { fiber: 2, sodium: 780, sugar: 7, potassium: 720, calcium: 50, iron: 3, vitaminC: 10 },
    prep: "2 hr", cook: "10 min", makes: 4,
    ingredients: [
      "1.5 lb top sirloin, sliced paper thin",
      "1/2 Asian pear, grated",
      "1/4 cup low sodium soy sauce",
      "1 tbsp coconut sugar",
      "1 tbsp sesame oil",
      "6 garlic cloves, minced",
      "1 tbsp grated ginger",
      "3 scallions, sliced",
      "1 tsp toasted sesame seeds",
      "1 head red leaf lettuce",
      "Ssamjang for serving",
    ],
    steps: [
      "Freeze the sirloin 30 minutes before slicing. It makes paper thin cuts possible.",
      "Mix the grated pear, soy sauce, coconut sugar, sesame oil, garlic, and ginger. The pear enzyme tenderizes the meat.",
      "Marinate the beef 2 hours in the refrigerator. Do not go past 6 hours or it turns mushy.",
      "Heat a cast iron skillet over high until it is nearly smoking.",
      "Cook the beef in batches in a single layer, 90 seconds per side. Crowding the pan steams it instead of searing it.",
      "Finish with scallions and sesame seeds.",
      "Serve with lettuce leaves and a small spoon of ssamjang per wrap.",
    ],
  },
  {
    id: "kr-dak-gochujang",
    cuisine: "korean",
    name: "Gochujang Dak Gui",
    blurb: "Broiled gochujang chicken. Big flavor for very little fat.",
    image: "/images/Cookbook/kr-dak-gochujang.jpg",
    macros: { calories: 315, protein: 47, carbs: 15, fat: 8 },
    micros: { fiber: 2, sodium: 820, sugar: 8, potassium: 680, calcium: 40, iron: 2.2, vitaminC: 6 },
    prep: "1 hr", cook: "18 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "3 tbsp gochujang",
      "2 tbsp low sodium soy sauce",
      "1 tbsp rice vinegar",
      "1 tbsp coconut sugar",
      "1 tbsp grated ginger",
      "5 garlic cloves, minced",
      "1 tsp sesame oil",
      "1 tsp gochugaru",
      "3 scallions, sliced",
      "1 tsp toasted sesame seeds",
    ],
    steps: [
      "Whisk the gochujang, soy sauce, rice vinegar, coconut sugar, ginger, garlic, sesame oil, and gochugaru together.",
      "Coat the chicken and marinate at least 1 hour, overnight if you can.",
      "Heat the broiler to high with a rack 6 inches down. Line a sheet pan with foil and set a wire rack on it.",
      "Spread the chicken on the rack in a single layer.",
      "Broil 9 minutes, flip, then broil 7 to 9 more until the edges blacken in spots.",
      "Watch the last 3 minutes closely. Gochujang has sugar in it and goes from caramelized to burnt fast.",
      "Rest 5 minutes, slice, and finish with scallions and sesame seeds.",
    ],
  },
  {
    id: "kr-bibimbap",
    cuisine: "korean",
    name: "Bibimbap",
    blurb: "Every vegetable seasoned separately. That is the whole point of the dish.",
    image: "/images/Cookbook/kr-bibimbap.jpg",
    macros: { calories: 440, protein: 42, carbs: 38, fat: 14 },
    micros: { fiber: 7, sodium: 860, sugar: 7, potassium: 1100, calcium: 140, iron: 4.6, vitaminC: 26 },
    prep: "30 min", cook: "20 min", makes: 4,
    ingredients: [
      "1 lb lean ground beef (93%)",
      "2 cups cooked short grain brown rice",
      "8 oz spinach, blanched and squeezed dry",
      "1 cup bean sprouts, blanched",
      "1 carrot, julienned and sauteed",
      "8 oz shiitake mushrooms, sliced and sauteed",
      "1 zucchini, julienned and sauteed",
      "4 eggs",
      "3 tbsp gochujang",
      "1 tbsp sesame oil",
      "2 tbsp low sodium soy sauce",
      "4 garlic cloves, minced",
      "Toasted sesame seeds",
    ],
    steps: [
      "Season each vegetable separately after cooking: a little sesame oil, minced garlic, salt, and sesame seeds on each one. Keep them in separate piles.",
      "Brown the ground beef with the soy sauce and 1 clove of garlic, about 8 minutes.",
      "Mix the gochujang with 1 tsp sesame oil and 1 tbsp water to make it spoonable.",
      "Fry the eggs sunny side up in a nonstick pan, keeping the yolks runny.",
      "Build each bowl: 1/2 cup rice on the bottom, then the vegetables arranged in wedges around the edge.",
      "Set the beef in the center and the egg on top of the beef.",
      "Add the gochujang sauce and mix everything together hard right before the first bite.",
    ],
  },

  /* ─── GREEK ──────────────────────────────────────────────────────── */
  {
    id: "gr-souvlaki",
    cuisine: "greek",
    name: "Chicken Souvlaki with Tzatziki",
    blurb: "Lemon and oregano chicken with a yogurt sauce that stays lean.",
    image: "/images/Cookbook/gr-souvlaki.jpg",
    macros: { calories: 350, protein: 52, carbs: 10, fat: 11 },
    micros: { fiber: 1, sodium: 620, sugar: 4, potassium: 780, calcium: 120, iron: 1.4, vitaminC: 8 },
    prep: "2 hr", cook: "12 min", makes: 4,
    ingredients: [
      "2 lb chicken breast, cut into 1.5 inch cubes",
      "1/4 cup fresh lemon juice",
      "2 tbsp olive oil",
      "6 garlic cloves, minced",
      "1 tbsp dried oregano",
      "1 tsp salt",
      "1 cup nonfat Greek yogurt",
      "1 Persian cucumber, grated and squeezed dry",
      "1 garlic clove, grated, for the tzatziki",
      "1 tbsp lemon juice for the tzatziki",
      "1 tbsp chopped dill",
    ],
    steps: [
      "Whisk the lemon juice, olive oil, garlic, oregano, and salt. Marinate the chicken 2 to 4 hours.",
      "Make the tzatziki: mix the yogurt, squeezed cucumber, grated garlic, lemon juice, and dill. Salt it and chill at least 30 minutes so the flavors set.",
      "Soak wooden skewers 20 minutes if you are using them. Thread the chicken with small gaps between cubes.",
      "Heat a grill or grill pan to high.",
      "Grill 5 to 6 minutes per side until charred outside and 165F inside.",
      "Rest 5 minutes before pulling the chicken off the skewers.",
      "Serve with the tzatziki and a lemon wedge.",
    ],
  },
  {
    id: "gr-bakaliaros-plaki",
    cuisine: "greek",
    name: "Psari Plaki",
    blurb: "Cod baked over tomatoes and onions. One dish, one pan.",
    image: "/images/Cookbook/gr-bakaliaros-plaki.jpg",
    macros: { calories: 260, protein: 31, carbs: 16, fat: 8 },
    micros: { fiber: 4, sodium: 480, sugar: 8, potassium: 1050, calcium: 90, iron: 1.6, vitaminC: 30 },
    prep: "15 min", cook: "35 min", makes: 4,
    ingredients: [
      "4 cod fillets (6 oz each)",
      "1 tbsp olive oil",
      "2 onions, sliced thin",
      "5 garlic cloves, sliced",
      "1 can (14 oz) diced tomatoes",
      "1 tsp dried oregano",
      "1/4 cup chopped parsley",
      "1/4 cup dry white wine",
      "1 lemon, sliced",
      "Salt and black pepper",
    ],
    steps: [
      "Heat the oven to 375F.",
      "Heat the oil in an oven safe skillet over medium. Cook the onions 10 minutes until soft and sweet.",
      "Add the garlic and oregano. Cook 1 minute.",
      "Add the tomatoes and wine. Simmer 8 minutes until it thickens.",
      "Stir in half the parsley and season the sauce well. It has to carry the fish.",
      "Nestle the cod into the sauce and top each fillet with a lemon slice.",
      "Bake uncovered 18 minutes, until the fish flakes at the center.",
      "Finish with the remaining parsley.",
    ],
  },
  {
    id: "gr-horiatiki-garides",
    cuisine: "greek",
    name: "Horiatiki with Grilled Shrimp",
    blurb: "Village salad with shrimp on top. No lettuce, that is the traditional version.",
    image: "/images/Cookbook/gr-horiatiki-garides.jpg",
    macros: { calories: 360, protein: 45, carbs: 14, fat: 14 },
    micros: { fiber: 4, sodium: 880, sugar: 8, potassium: 780, calcium: 220, iron: 1.8, vitaminC: 60 },
    prep: "15 min", cook: "6 min", makes: 2,
    ingredients: [
      "1 lb large shrimp, peeled and deveined",
      "3 large tomatoes, cut into wedges",
      "1 cucumber, cut into thick half moons",
      "1/2 red onion, sliced thin",
      "1 green bell pepper, sliced",
      "1/3 cup kalamata olives",
      "2 oz feta, in one slab",
      "1 tbsp olive oil",
      "1 tbsp red wine vinegar",
      "1 tsp dried oregano",
      "1 tsp olive oil for the shrimp",
    ],
    steps: [
      "Toss the shrimp with 1 tsp olive oil, salt, and pepper.",
      "Heat a grill pan over high. Cook the shrimp 2 to 3 minutes per side until pink and lightly charred.",
      "Combine the tomatoes, cucumber, onion, pepper, and olives in a wide bowl.",
      "Dress with 1 tbsp olive oil, the vinegar, and salt. Toss gently.",
      "Lay the feta slab whole on top. Do not crumble it, that is the Greek way and it also portions better.",
      "Sprinkle the oregano over the feta.",
      "Arrange the shrimp around the edge and serve right away.",
    ],
  },

  /* ─── MIDDLE EASTERN ─────────────────────────────────────────────── */
  {
    id: "me-shawarma-bowl",
    cuisine: "middle-eastern",
    name: "Chicken Shawarma Bowl",
    blurb: "Oven shawarma over salad with a thinned tahini sauce.",
    image: "/images/Cookbook/me-shawarma-bowl.jpg",
    macros: { calories: 430, protein: 50, carbs: 18, fat: 18 },
    micros: { fiber: 5, sodium: 640, sugar: 5, potassium: 980, calcium: 140, iron: 3.4, vitaminC: 26 },
    prep: "4 hr", cook: "30 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "1/4 cup fresh lemon juice",
      "2 tbsp olive oil",
      "6 garlic cloves, minced",
      "2 tsp ground cumin",
      "2 tsp paprika",
      "1 tsp ground coriander",
      "1 tsp ground turmeric",
      "1/2 tsp ground cinnamon",
      "1/4 cup tahini",
      "2 tbsp lemon juice for the sauce",
      "1/4 cup cold water",
      "4 cups chopped romaine, tomato, cucumber, and parsley",
    ],
    steps: [
      "Whisk the lemon juice, olive oil, garlic, and all the spices into a marinade.",
      "Coat the chicken and refrigerate at least 4 hours, overnight is better.",
      "Heat the oven to 425F. Spread the chicken on a lined sheet pan in a single layer.",
      "Roast 25 minutes, then broil 3 to 5 minutes to get char on the edges.",
      "Make the sauce: whisk the tahini with lemon juice. It will seize and look broken. Keep whisking and add the cold water a splash at a time until it turns smooth and pourable.",
      "Rest the chicken 5 minutes, then slice it thin.",
      "Build the bowls with the chopped salad, then the chicken, then the tahini sauce over the top.",
    ],
  },
  {
    id: "me-shish-tawook",
    cuisine: "middle-eastern",
    name: "Shish Tawook",
    blurb: "Yogurt and garlic chicken skewers. Lean, tender, and grill ready.",
    image: "/images/Cookbook/me-shish-tawook.jpg",
    macros: { calories: 300, protein: 51, carbs: 6, fat: 8 },
    micros: { fiber: 1, sodium: 680, sugar: 3, potassium: 740, calcium: 90, iron: 1.3, vitaminC: 10 },
    prep: "6 hr", cook: "12 min", makes: 4,
    ingredients: [
      "2 lb chicken breast, cut into 1.5 inch cubes",
      "1/2 cup nonfat Greek yogurt",
      "1/4 cup fresh lemon juice",
      "8 garlic cloves, grated",
      "1 tbsp tomato paste",
      "1 tbsp olive oil",
      "1 tsp paprika",
      "1 tsp dried oregano",
      "1/2 tsp ground allspice",
      "1 tsp salt",
      "Sumac to finish",
    ],
    steps: [
      "Whisk the yogurt, lemon juice, garlic, tomato paste, olive oil, and all the spices together.",
      "Fold in the chicken and refrigerate 6 hours minimum. The yogurt tenderizes slowly, so overnight is ideal.",
      "Thread onto skewers with small gaps so the heat gets between the pieces.",
      "Heat a grill to high. Oil the grates.",
      "Grill 5 to 6 minutes per side. The yogurt coating will blister and spot black, which is what you want.",
      "Rest 5 minutes and dust with sumac before serving.",
    ],
  },
  {
    id: "me-kofta-lean",
    cuisine: "middle-eastern",
    name: "Lean Beef Kofta",
    blurb: "Herb heavy kofta made with 96% lean beef. Bulk it with parsley, not fat.",
    image: "/images/Cookbook/me-kofta-lean.jpg",
    macros: { calories: 290, protein: 42, carbs: 7, fat: 10 },
    micros: { fiber: 2, sodium: 700, sugar: 2, potassium: 720, calcium: 60, iron: 4, vitaminC: 22 },
    prep: "20 min", cook: "12 min", makes: 4,
    ingredients: [
      "1.5 lb 96% lean ground beef",
      "1 onion, grated and squeezed dry",
      "1 cup finely chopped parsley",
      "4 garlic cloves, minced",
      "2 tsp ground cumin",
      "1 tsp ground coriander",
      "1 tsp paprika",
      "1/2 tsp ground cinnamon",
      "1/2 tsp ground allspice",
      "1 tsp salt",
      "1 egg white",
    ],
    steps: [
      "Squeeze every drop of liquid out of the grated onion. Wet onion makes the kofta fall apart on the grill.",
      "Mix the beef, onion, parsley, garlic, spices, salt, and egg white by hand for a full 2 minutes. Working it hard is what binds lean beef.",
      "Chill the mixture 20 minutes.",
      "Shape into 8 logs around flat skewers, pressing firmly so they grip.",
      "Heat a grill or grill pan to medium high.",
      "Cook 5 to 6 minutes per side, turning once only. Flipping repeatedly breaks them.",
      "Rest 3 minutes and serve with lemon.",
    ],
  },

  /* ─── BRAZILIAN ──────────────────────────────────────────────────── */
  {
    id: "br-frango-vinagrete",
    cuisine: "brazilian",
    name: "Frango Grelhado com Vinagrete",
    blurb: "Grilled chicken with a raw tomato salsa. The default Brazilian plate.",
    image: "/images/Cookbook/br-frango-vinagrete.jpg",
    macros: { calories: 330, protein: 50, carbs: 12, fat: 9 },
    micros: { fiber: 3, sodium: 640, sugar: 6, potassium: 900, calcium: 50, iron: 1.8, vitaminC: 48 },
    prep: "1 hr", cook: "14 min", makes: 4,
    ingredients: [
      "2 lb chicken breast, butterflied",
      "1/4 cup fresh lime juice",
      "6 garlic cloves, minced",
      "1 tbsp olive oil",
      "1 tsp salt",
      "3 tomatoes, diced small",
      "1 onion, diced small",
      "1 green bell pepper, diced small",
      "1/4 cup chopped parsley",
      "3 tbsp red wine vinegar",
      "1 tbsp olive oil for the vinagrete",
    ],
    steps: [
      "Mix the lime juice, garlic, 1 tbsp olive oil, and salt. Marinate the chicken 1 hour.",
      "Make the vinagrete: combine the tomato, onion, pepper, parsley, vinegar, and 1 tbsp olive oil. Salt it and let it sit 30 minutes.",
      "Heat a grill to high and oil the grates.",
      "Grill the chicken 6 to 7 minutes per side until it hits 165F.",
      "Rest 5 minutes, then slice against the grain.",
      "Spoon the vinagrete over the sliced chicken, including the liquid at the bottom of the bowl.",
    ],
  },
  {
    id: "br-moqueca",
    cuisine: "brazilian",
    name: "Moqueca de Peixe",
    blurb: "Coconut fish stew with the coconut milk cut with broth.",
    image: "/images/Cookbook/br-moqueca.jpg",
    macros: { calories: 355, protein: 40, carbs: 14, fat: 16 },
    micros: { fiber: 3, sodium: 560, sugar: 6, potassium: 1050, calcium: 80, iron: 1.8, vitaminC: 70 },
    prep: "15 min", cook: "25 min", makes: 4,
    ingredients: [
      "2 lb firm white fish, cut into large chunks",
      "3 tbsp fresh lime juice",
      "1 tbsp avocado oil",
      "1 onion, sliced",
      "2 bell peppers, sliced",
      "5 garlic cloves, minced",
      "3 tomatoes, sliced",
      "1 cup light coconut milk",
      "1 cup low sodium fish or chicken broth",
      "1 tbsp dende oil, optional",
      "1 tsp paprika",
      "1/2 cup chopped cilantro",
    ],
    steps: [
      "Toss the fish with the lime juice, salt, and pepper. Rest 15 minutes.",
      "Heat the oil in a wide pot over medium. Cook the onion and peppers 8 minutes.",
      "Add the garlic and paprika. Cook 1 minute.",
      "Layer the tomato slices over the vegetables, then pour in the coconut milk and broth.",
      "Bring to a bare simmer. Do not boil coconut milk or it splits.",
      "Lay the fish on top in a single layer. Cover and simmer 10 minutes without stirring, so the chunks stay whole.",
      "Add the dende oil if you are using it, plus half the cilantro.",
      "Finish with the remaining cilantro and serve in bowls.",
    ],
  },
  {
    id: "br-carne-panela",
    cuisine: "brazilian",
    name: "Carne de Panela Magra",
    blurb: "Braised lean beef and vegetables. Cheap protein and it improves overnight.",
    image: "/images/Cookbook/br-carne-panela.jpg",
    macros: { calories: 370, protein: 45, carbs: 22, fat: 11 },
    micros: { fiber: 4, sodium: 580, sugar: 7, potassium: 980, calcium: 60, iron: 4.2, vitaminC: 12 },
    prep: "15 min", cook: "2 hr", makes: 6,
    ingredients: [
      "2.5 lb bottom round or chuck, trimmed hard and cubed",
      "1 tbsp avocado oil",
      "2 onions, diced",
      "6 garlic cloves, minced",
      "3 tbsp tomato paste",
      "3 cups low sodium beef broth",
      "3 carrots, cut into thick coins",
      "2 bay leaves",
      "1 tsp ground cumin",
      "1 tbsp red wine vinegar",
      "1/4 cup chopped parsley",
    ],
    steps: [
      "Season the beef with salt and pepper. Heat the oil in a Dutch oven over high.",
      "Sear the beef in batches until browned on all sides. Crowding the pot kills the crust.",
      "Set the beef aside. Lower to medium and cook the onions 8 minutes.",
      "Add the garlic and cumin, cook 1 minute, then the tomato paste and cook 2 minutes until it darkens.",
      "Return the beef with the broth and bay leaves. Bring to a simmer.",
      "Cover and cook low for 90 minutes.",
      "Add the carrots and cook 30 more minutes, until the beef pulls apart with a fork.",
      "Stir in the vinegar to brighten it, pull the bay leaves, and finish with parsley.",
    ],
  },

  /* ─── SPANISH ────────────────────────────────────────────────────── */
  {
    id: "es-pollo-ajillo",
    cuisine: "spanish",
    name: "Pollo al Ajillo",
    blurb: "A whole head of garlic and a splash of sherry. Twenty five minutes.",
    image: "/images/Cookbook/es-pollo-ajillo.jpg",
    macros: { calories: 340, protein: 47, carbs: 6, fat: 13 },
    micros: { fiber: 1, sodium: 560, sugar: 1, potassium: 680, calcium: 40, iron: 2, vitaminC: 8 },
    prep: "10 min", cook: "25 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs, cut into large pieces",
      "1 whole head of garlic, cloves peeled and smashed",
      "1 tbsp olive oil",
      "1/2 cup dry sherry",
      "1/2 cup low sodium chicken broth",
      "2 bay leaves",
      "1 tsp smoked paprika",
      "1/4 cup chopped parsley",
      "Salt and black pepper",
    ],
    steps: [
      "Season the chicken well. Heat the oil in a wide skillet over medium high.",
      "Sear the chicken 4 minutes per side until browned. Set it aside.",
      "Drop the heat to medium low. Add all the garlic and cook 4 minutes, stirring, until golden and soft. Burnt garlic ruins this dish.",
      "Add the smoked paprika and stir 20 seconds.",
      "Pour in the sherry and reduce by half, about 3 minutes.",
      "Return the chicken with the broth and bay leaves.",
      "Simmer uncovered 10 minutes until the sauce tightens and coats the chicken.",
      "Pull the bay leaves and finish with parsley.",
    ],
  },
  {
    id: "es-gambas-ajillo",
    cuisine: "spanish",
    name: "Gambas al Ajillo",
    blurb: "Ten minutes, high protein, and almost no carbs.",
    image: "/images/Cookbook/es-gambas-ajillo.jpg",
    macros: { calories: 230, protein: 35, carbs: 4, fat: 9 },
    micros: { fiber: 1, sodium: 720, sugar: 1, potassium: 420, calcium: 90, iron: 1, vitaminC: 8 },
    prep: "5 min", cook: "8 min", makes: 4,
    ingredients: [
      "1.5 lb large shrimp, peeled and deveined",
      "8 garlic cloves, sliced thin",
      "2 tbsp olive oil",
      "1 dried chile de arbol, crumbled",
      "1 tsp smoked paprika",
      "2 tbsp dry sherry",
      "2 tbsp fresh lemon juice",
      "1/4 cup chopped parsley",
      "Salt",
    ],
    steps: [
      "Pat the shrimp completely dry and salt them. Wet shrimp steam instead of sear.",
      "Heat the oil in a skillet over medium. Add the garlic and dried chile.",
      "Cook 3 minutes until the garlic turns pale gold. Pull it early, it keeps cooking in the oil.",
      "Turn the heat to high. Add the shrimp in a single layer and cook 90 seconds without moving them.",
      "Flip, add the smoked paprika and sherry, and cook 90 seconds more.",
      "Kill the heat. Add the lemon juice and parsley and toss.",
      "Serve immediately with the pan oil spooned over.",
    ],
  },
  {
    id: "es-merluza-plancha",
    cuisine: "spanish",
    name: "Merluza a la Plancha con Pisto",
    blurb: "Seared hake over a slow cooked vegetable base.",
    image: "/images/Cookbook/es-merluza-plancha.jpg",
    macros: { calories: 275, protein: 31, carbs: 18, fat: 9 },
    micros: { fiber: 5, sodium: 480, sugar: 9, potassium: 1080, calcium: 70, iron: 1.6, vitaminC: 90 },
    prep: "15 min", cook: "40 min", makes: 4,
    ingredients: [
      "4 hake or cod fillets (6 oz each)",
      "1 tbsp olive oil for the pisto",
      "1 onion, diced",
      "1 zucchini, diced",
      "1 red bell pepper, diced",
      "1 green bell pepper, diced",
      "4 garlic cloves, minced",
      "1 can (14 oz) crushed tomatoes",
      "1 tsp smoked paprika",
      "1 tsp olive oil for searing",
      "Salt and black pepper",
    ],
    steps: [
      "Heat 1 tbsp oil in a wide pan over medium. Cook the onion and both peppers 12 minutes.",
      "Add the zucchini and garlic. Cook 8 minutes.",
      "Add the tomatoes and smoked paprika. Simmer uncovered 20 minutes until it thickens to a jam. That is the pisto.",
      "Pat the fish dry and season both sides.",
      "Heat 1 tsp oil in a nonstick pan over high until it shimmers.",
      "Sear the fish 4 minutes on the first side without touching it, then 2 minutes on the second.",
      "Spoon the pisto onto plates and set the fish on top so the crust stays dry.",
    ],
  },

  /* ─── AFRICAN ────────────────────────────────────────────────────── */
  {
    id: "af-peri-peri",
    cuisine: "african",
    name: "Peri Peri Chicken",
    blurb: "Mozambican style chili and lemon chicken, roasted hot.",
    image: "/images/Cookbook/af-peri-peri.jpg",
    macros: { calories: 345, protein: 48, carbs: 8, fat: 13 },
    micros: { fiber: 2, sodium: 640, sugar: 4, potassium: 780, calcium: 40, iron: 2, vitaminC: 70 },
    prep: "4 hr", cook: "35 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "8 red chilies, stemmed",
      "1 red bell pepper, roasted and peeled",
      "6 garlic cloves",
      "1/4 cup fresh lemon juice",
      "2 tbsp red wine vinegar",
      "1 tbsp olive oil",
      "1 tbsp smoked paprika",
      "1 tsp dried oregano",
      "1 tsp salt",
    ],
    steps: [
      "Blend the chilies, roasted pepper, garlic, lemon juice, vinegar, olive oil, paprika, oregano, and salt until smooth.",
      "Reserve a third of the sauce for serving. Marinate the chicken in the rest for at least 4 hours.",
      "Heat the oven to 425F. Spread the chicken on a lined sheet pan.",
      "Roast 25 minutes, basting once at the halfway mark.",
      "Broil 4 to 6 minutes to char the edges.",
      "Rest 5 minutes.",
      "Serve with the reserved sauce spooned over. Never reuse the marinade the raw chicken sat in.",
    ],
  },
  {
    id: "af-doro-wat",
    cuisine: "african",
    name: "Doro Wat Ligero",
    blurb: "Ethiopian chicken stew with the butter cut way back. Berbere carries it.",
    image: "/images/Cookbook/af-doro-wat.jpg",
    macros: { calories: 330, protein: 46, carbs: 16, fat: 10 },
    micros: { fiber: 4, sodium: 700, sugar: 7, potassium: 820, calcium: 70, iron: 3.2, vitaminC: 14 },
    prep: "15 min", cook: "1 hr", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "4 large onions, diced very fine",
      "1 tbsp niter kibbeh or clarified butter",
      "1/4 cup berbere spice",
      "1 tbsp grated ginger",
      "6 garlic cloves, minced",
      "2 tbsp tomato paste",
      "2 cups low sodium chicken broth",
      "2 tbsp fresh lemon juice",
      "4 hard boiled eggs, peeled",
    ],
    steps: [
      "Cook the onions in a dry pot over medium low for 20 minutes, stirring often. No oil yet. They release their own water and collapse into a paste.",
      "Add the niter kibbeh, ginger, and garlic. Cook 5 minutes.",
      "Add the berbere and tomato paste. Cook 3 minutes, stirring constantly so it does not scorch.",
      "Add 1 cup broth and simmer 5 minutes.",
      "Add the chicken and the remaining broth. Cover and simmer 30 minutes.",
      "Uncover and simmer 10 minutes to reduce until the sauce clings to the chicken.",
      "Score the hard boiled eggs shallowly and add them for the last 5 minutes so they take on color.",
      "Finish with lemon juice.",
    ],
  },
  {
    id: "af-tagine-djaj",
    cuisine: "african",
    name: "Chicken Tagine with Olives and Lemon",
    blurb: "Moroccan tagine, no added sugar and no dried fruit.",
    image: "/images/Cookbook/af-tagine-djaj.jpg",
    macros: { calories: 350, protein: 47, carbs: 13, fat: 12 },
    micros: { fiber: 3, sodium: 780, sugar: 5, potassium: 800, calcium: 60, iron: 2.4, vitaminC: 14 },
    prep: "15 min", cook: "50 min", makes: 4,
    ingredients: [
      "2 lb boneless skinless chicken thighs",
      "1 tbsp olive oil",
      "2 onions, sliced thin",
      "5 garlic cloves, minced",
      "1 tsp ground ginger",
      "1 tsp ground turmeric",
      "1 tsp ground cumin",
      "1/2 tsp ground cinnamon",
      "Pinch of saffron threads",
      "1.5 cups low sodium chicken broth",
      "1 preserved lemon, rinsed and sliced thin",
      "1/2 cup green olives",
      "1/2 cup chopped cilantro and parsley",
    ],
    steps: [
      "Bloom the saffron in 2 tbsp of warm broth for 10 minutes.",
      "Season the chicken. Heat the oil in a heavy pot over medium high and sear 4 minutes per side. Set it aside.",
      "Lower to medium. Cook the onions 10 minutes until soft.",
      "Add the garlic, ginger, turmeric, cumin, and cinnamon. Cook 90 seconds.",
      "Return the chicken with the broth and the bloomed saffron.",
      "Cover and simmer low 30 minutes.",
      "Add the preserved lemon and olives. Simmer uncovered 10 minutes to reduce the sauce.",
      "Finish with the chopped herbs.",
    ],
  },
];

/* Helper: pull every recipe for one cuisine id. */
export function recipesByCuisine(cuisineId) {
  return RECIPES.filter((r) => r.cuisine === cuisineId);
}

/* Helper: look one up by id. Used by the tracker when logging a recipe. */
export function recipeById(id) {
  return RECIPES.find((r) => r.id === id) || null;
}
